name: "Pull Request Labeler"
on:
  pull_request_target:

env:
  LABELER_CONFIG: '.github/labeler.yml'

permissions: read-all

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone Labeler configuration
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        sparse-checkout: ${{ env.LABELER_CONFIG }}

    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ${{ env.LABELER_CONFIG }}
        sync-labels: 'true'
